image: node:16-buster-slim

cache:
  paths:
    - node_modules/

pages:
  stage: deploy
  script:
  - npm install -y
  - npm run build --verbose
  - mkdir .public
  - cp -r * .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
    - main 
